[package]
name = "simple-log"
version = "0.1.0"
authors = ["Joel McCracken <mccracken.joel@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }

[dependencies.nickel]
git = "https://github.com/nickel-org/nickel.rs.git"
