[package]
name = "clap-cli"
version = "0.1.0"
edition = "2024"

[dependencies]

chrono = "0.2"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }

[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"
